import {
  Users,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  UserCog,
  Building2,
  ScanSearch,
  Target,
  Activity,
  ShieldCheck,
  BarChart3,
  TriangleAlert,
  Info,
  User,
  FileText,
  Heart,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  users: Users,
  userCheck: UserCheck,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userX: UserX,
  userCog: UserCog,
  building: Building2,
  scanSearch: ScanSearch,
  target: Target,
  activity: Activity,
  shieldCheck: ShieldCheck,
  barChart: BarChart3,
  alert: TriangleAlert,
  info: Info,
  user: User,
  fileText: FileText,
  heart: Heart,
};
